-- Removed categories table insert since it doesn't exist in schema
-- Add comprehensive fruits list to products
INSERT INTO products (name, name_hi, name_gu, description, description_hi, description_gu, category, origin_country, harvest_season, shelf_life, packaging_options, min_order_quantity, price_per_unit, currency, image_url, is_featured, is_active) VALUES
-- Citrus Fruits
('Fresh Oranges', 'ताजे संतरे', 'તાજા નારંગી', 'Juicy and sweet oranges, rich in Vitamin C and perfect for fresh consumption and juice production.', 'रसदार और मीठे संतरे, विटामिन सी से भरपूर और ताजा सेवन और रस उत्पादन के लिए उपयुक्त।', 'રસાળ અને મીઠા નારંગી, વિટામિન સીથી ભરપૂર અને તાજા સેવન અને રસ ઉત્પાદન માટે યોગ્ય।', 'Citrus', 'India', 'November - March', '14-21 days', ARRAY['10kg boxes', '15kg boxes', 'Bulk containers'], 250, 3.20, 'USD', '/placeholder.svg?height=300&width=400', false, true),
('Premium Lemons', 'प्रीमियम नींबू', 'પ્રીમિયમ લીંબુ', 'High-quality lemons with excellent acidity and aroma, ideal for culinary and beverage industries.', 'उत्कृष्ट अम्लता और सुगंध वाले उच्च गुणवत्ता वाले नींबू, पाक और पेय उद्योगों के लिए आदर्श।', 'ઉત્કૃષ્ટ એસિડિટી અને સુગંધ સાથે ઉચ્ચ ગુણવત્તાવાળા લીંબુ, રસોઈ અને પીણા ઉદ્યોગો માટે આદર્શ।', 'Citrus', 'India', 'Year-round', '21-28 days', ARRAY['5kg boxes', '10kg boxes'], 200, 2.80, 'USD', '/placeholder.svg?height=300&width=400', false, true),
('Sweet Limes', 'मीठे मौसमी', 'મીઠા મોસંબી', 'Sweet and refreshing limes with low acidity, perfect for direct consumption.', 'कम अम्लता वाले मीठे और ताज़गी देने वाले मौसमी, सीधे सेवन के लिए उपयुक्त।', 'ઓછી એસિડિટી સાથે મીઠા અને તાજગી આપનારા મોસંબી, સીધા સેવન માટે યોગ્ય।', 'Citrus', 'India', 'October - March', '10-14 days', ARRAY['8kg boxes', '12kg boxes'], 180, 3.50, 'USD', '/placeholder.svg?height=300&width=400', false, true),

-- Tropical Fruits
('Fresh Pineapples', 'ताजे अनानास', 'તાજા અનાનસ', 'Sweet and tangy pineapples, rich in enzymes and perfect for fresh consumption and processing.', 'मीठे और तीखे अनानास, एंजाइमों से भरपूर और ताजा सेवन और प्रसंस्करण के लिए उपयुक्त।', 'મીઠા અને તીખા અનાનસ, એન્ઝાઇમથી ભરપૂર અને તાજા સેવન અને પ્રોસેસિંગ માટે યોગ્ય।', 'Tropical', 'India', 'March - June', '7-10 days', ARRAY['Individual packaging', '6-piece boxes'], 100, 4.50, 'USD', '/placeholder.svg?height=300&width=400', false, true),
('Fresh Coconuts', 'ताजे नारियल', 'તાજા નાળિયેર', 'Fresh tender coconuts with sweet water and soft meat, perfect for natural hydration.', 'मीठे पानी और नरम गूदे वाले ताजे कोमल नारियल, प्राकृतिक हाइड्रेशन के लिए उपयुक्त।', 'મીઠા પાણી અને નરમ ગૂદા સાથે તાજા કોમળ નાળિયેર, કુદરતી હાઇડ્રેશન માટે યોગ્ય।', 'Tropical', 'India', 'Year-round', '15-20 days', ARRAY['Individual packaging', '12-piece boxes'], 150, 2.20, 'USD', '/placeholder.svg?height=300&width=400', false, true),
('Fresh Papayas', 'ताजे पपीते', 'તાજા પપૈયા', 'Sweet and nutritious papayas, rich in vitamins and digestive enzymes.', 'मीठे और पौष्टिक पपीते, विटामिन और पाचन एंजाइमों से भरपूर।', 'મીઠા અને પોષક પપૈયા, વિટામિન અને પાચન એન્ઝાઇમથી ભરપૂર।', 'Tropical', 'India', 'Year-round', '5-7 days', ARRAY['Individual packaging', '6-piece boxes'], 120, 3.80, 'USD', '/placeholder.svg?height=300&width=400', false, true),

-- Stone Fruits
('Fresh Apples', 'ताजे सेब', 'તાજા સફરજન', 'Crisp and sweet apples from Kashmir, known for their excellent taste and long shelf life.', 'कश्मीर के कुरकुरे और मीठे सेब, अपने उत्कृष्ट स्वाद और लंबी शेल्फ लाइफ के लिए जाने जाते हैं।', 'કાશ્મીરના કડક અને મીઠા સફરજન, તેમના ઉત્કૃષ્ટ સ્વાદ અને લાંબી શેલ્ફ લાઇફ માટે જાણીતા છે।', 'Stone Fruits', 'India', 'August - November', '30-45 days', ARRAY['10kg boxes', '18kg boxes'], 300, 5.20, 'USD', '/placeholder.svg?height=300&width=400', true, true),
('Fresh Pears', 'ताजे नाशपाती', 'તાજા નાશપાતી', 'Juicy and sweet pears with delicate flavor and smooth texture.', 'नाजुक स्वाद और चिकनी बनावट वाले रसदार और मीठे नाशपाती।', 'નાજુક સ્વાદ અને સરળ ટેક્સચર સાથે રસાળ અને મીઠા નાશપાતી।', 'Stone Fruits', 'India', 'July - October', '21-28 days', ARRAY['8kg boxes', '15kg boxes'], 200, 6.80, 'USD', '/placeholder.svg?height=300&width=400', false, true),
('Fresh Plums', 'ताजे आलूबुखारे', 'તાજા આલુબુખારા', 'Sweet and tangy plums with vibrant colors and rich flavor profile.', 'जीवंत रंगों और समृद्ध स्वाद प्रोफ़ाइल वाले मीठे और तीखे आलूबुखारे।', 'જીવંત રંગો અને સમૃદ્ધ સ્વાદ પ્રોફાઇલ સાથે મીઠા અને તીખા આલુબુખારા।', 'Stone Fruits', 'India', 'May - August', '7-10 days', ARRAY['5kg boxes', '10kg boxes'], 150, 7.50, 'USD', '/placeholder.svg?height=300&width=400', false, true),

-- Berries
('Fresh Strawberries', 'ताजे स्ट्रॉबेरी', 'તાજા સ્ટ્રોબેરી', 'Premium strawberries with intense flavor and aroma, perfect for gourmet markets.', 'तीव्र स्वाद और सुगंध वाली प्रीमियम स्ट्रॉबेरी, गॉरमेट बाजारों के लिए उपयुक्त।', 'તીવ્ર સ્વાદ અને સુગંધ સાથે પ્રીમિયમ સ્ટ્રોબેરી, ગોર્મેટ બજારો માટે યોગ્ય।', 'Berries', 'India', 'December - March', '3-5 days', ARRAY['250g punnets', '1kg boxes'], 50, 12.50, 'USD', '/placeholder.svg?height=300&width=400', true, true),

-- Exotic Fruits
('Dragon Fruit', 'ड्रैगन फ्रूट', 'ડ્રેગન ફ્રૂટ', 'Exotic dragon fruit with unique appearance and mild sweet flavor, rich in antioxidants.', 'अनोखी दिखावट और हल्के मीठे स्वाद वाला विदेशी ड्रैगन फ्रूट, एंटीऑक्सीडेंट से भरपूर।', 'અનોખા દેખાવ અને હળવા મીઠા સ્વાદ સાથે વિદેશી ડ્રેગન ફ્રૂટ, એન્ટીઑક્સીડન્ટથી ભરપૂર।', 'Exotic', 'India', 'June - November', '5-7 days', ARRAY['Individual packaging', '6-piece boxes'], 80, 15.00, 'USD', '/placeholder.svg?height=300&width=400', false, true),
('Fresh Kiwi', 'ताजे कीवी', 'તાજા કીવી', 'Nutrient-dense kiwi fruits with tangy-sweet flavor and high vitamin C content.', 'तीखे-मीठे स्वाद और उच्च विटामिन सी सामग्री वाले पोषक तत्वों से भरपूर कीवी फल।', 'તીખા-મીઠા સ્વાદ અને ઉચ્ચ વિટામિન સી સામગ્રી સાથે પોષક તત્વોથી ભરપૂર કીવી ફળ।', 'Exotic', 'India', 'October - February', '14-21 days', ARRAY['1kg boxes', '3kg boxes'], 100, 8.90, 'USD', '/placeholder.svg?height=300&width=400', false, true),

-- Melons
('Fresh Watermelons', 'ताजे तरबूज', 'તાજા તરબૂચ', 'Sweet and refreshing watermelons, perfect for hot climates and summer consumption.', 'मीठे और ताज़गी देने वाले तरबूज, गर्म जलवायु और गर्मियों के सेवन के लिए उपयुक्त।', 'મીઠા અને તાજગી આપનારા તરબૂચ, ગરમ આબોહવા અને ઉનાળાના સેવન માટે યોગ્ય।', 'Melons', 'India', 'March - June', '7-10 days', ARRAY['Individual packaging', 'Bulk containers'], 200, 1.80, 'USD', '/placeholder.svg?height=300&width=400', false, true),
('Fresh Muskmelons', 'ताजे खरबूजे', 'તાજા ખરબૂજા', 'Aromatic muskmelons with sweet flavor and high water content, ideal for summer.', 'मीठे स्वाद और उच्च पानी की मात्रा वाले सुगंधित खरबूजे, गर्मियों के लिए आदर्श।', 'મીઠા સ્વાદ અને ઉચ્ચ પાણીની માત્રા સાથે સુગંધિત ખરબૂજા, ઉનાળા માટે આદર્શ।', 'Melons', 'India', 'April - July', '5-7 days', ARRAY['Individual packaging', '6-piece boxes'], 150, 2.50, 'USD', '/placeholder.svg?height=300&width=400', false, true);
